In [1]:
import numpy as np 
import matplotlib.pyplot as plt
import glob
import cv2
import tensorflow as tf
from tensorflow import keras

from keras.models import Model, Sequential
from keras.layers import Dense, Flatten, Conv2D, MaxPooling2D
from tensorflow.keras.layers import BatchNormalization
from keras.layers import Dropout
#from keras.layers.normalization import BatchNormalization
#tf.keras.layers.BatchNormalization()
from tensorflow.keras.layers import BatchNormalization
import os
import seaborn as sns

In [2]:
SIZE = 128

In [3]:
train_images = []
train_labels = [] 

In [4]:
for directory_path in glob.glob("C:/Users/DIBYAJYOTI HALOI/Downloads/archive (1)/flowers/*"):
    label = directory_path.split("\\")[-1]
    print(label)
    i=0
    for img_path in glob.glob(os.path.join(directory_path, "*.jpg")):
        if i==250:
            break
        print(img_path)
        img = cv2.imread(img_path, cv2.IMREAD_COLOR)       
        img = cv2.resize(img, (SIZE, SIZE))
        #img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
        #img = color.rgb2gray(io.imread('img_path.jpg'))
        img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY )
        train_images.append(img)
        train_labels.append(label)
        i=i+1

astilbe
C:/Users/DIBYAJYOTI HALOI/Downloads/archive (1)/flowers\astilbe\10091895024_a2ea04cda6_c.jpg
C:/Users/DIBYAJYOTI HALOI/Downloads/archive (1)/flowers\astilbe\1033455028_f0c6518ec9_c.jpg
C:/Users/DIBYAJYOTI HALOI/Downloads/archive (1)/flowers\astilbe\10373087134_927b53fb9f_c.jpg
C:/Users/DIBYAJYOTI HALOI/Downloads/archive (1)/flowers\astilbe\1052212431_4963309d03_c.jpg
C:/Users/DIBYAJYOTI HALOI/Downloads/archive (1)/flowers\astilbe\1052219251_d03970e956_c.jpg
C:/Users/DIBYAJYOTI HALOI/Downloads/archive (1)/flowers\astilbe\1052586928_366c5255b8_c.jpg
C:/Users/DIBYAJYOTI HALOI/Downloads/archive (1)/flowers\astilbe\1052587144_34c9f0714c_c.jpg
C:/Users/DIBYAJYOTI HALOI/Downloads/archive (1)/flowers\astilbe\1053073526_188a5b816e_c.jpg
C:/Users/DIBYAJYOTI HALOI/Downloads/archive (1)/flowers\astilbe\1053075100_838051e5b7_c.jpg
C:/Users/DIBYAJYOTI HALOI/Downloads/archive (1)/flowers\astilbe\1053079170_650c3c6af6_c.jpg
C:/Users/DIBYAJYOTI HALOI/Downloads/archive (1)/flowers\astilbe\105308

In [5]:
len(train_images)

4000

In [6]:
from random import shuffle
shuffle(train_images)
train_images

[array([[39, 35, 46, ..., 16, 31, 40],
        [44, 41, 50, ..., 21, 39, 46],
        [54, 53, 56, ..., 26, 41, 44],
        ...,
        [39, 25, 32, ..., 12, 23, 45],
        [43,  9, 51, ..., 10, 32, 45],
        [56,  8, 47, ..., 49, 79, 34]], dtype=uint8),
 array([[ 94,  86,  69, ...,  82,  97,  64],
        [ 94, 104,  85, ...,  82, 139, 124],
        [ 95, 105,  98, ..., 106, 104, 121],
        ...,
        [ 27,  63, 109, ...,  10,  15,  21],
        [ 50,  62,  47, ...,   6,  10,  17],
        [ 62,  42,  28, ...,  18,  21,  21]], dtype=uint8),
 array([[ 61,   8,  22, ...,  56,  99,  70],
        [ 26,   7,   8, ...,  61, 181, 211],
        [ 15,  14,   6, ...,  75, 179, 177],
        ...,
        [117, 184, 174, ...,   8,   9,   5],
        [151, 171, 170, ...,  20,  26,  14],
        [126, 132, 163, ...,  32,  29,  23]], dtype=uint8),
 array([[ 0,  0,  0, ...,  0,  0,  0],
        [ 0,  0,  0, ...,  0,  0,  0],
        [ 0,  0,  0, ...,  0,  0,  0],
        ...,
        [59,

In [7]:
from random import shuffle
shuffle(train_labels)
train_labels

['california_poppy',
 'common_daisy',
 'dandelion',
 'rose',
 'daffodil',
 'iris',
 'iris',
 'dandelion',
 'dandelion',
 'daffodil',
 'calendula',
 'sunflower',
 'california_poppy',
 'dandelion',
 'daffodil',
 'sunflower',
 'bellflower',
 'rose',
 'bellflower',
 'black_eyed_susan',
 'sunflower',
 'calendula',
 'coreopsis',
 'common_daisy',
 'dandelion',
 'coreopsis',
 'water_lily',
 'magnolia',
 'rose',
 'common_daisy',
 'iris',
 'tulip',
 'common_daisy',
 'carnation',
 'iris',
 'black_eyed_susan',
 'daffodil',
 'coreopsis',
 'water_lily',
 'sunflower',
 'dandelion',
 'common_daisy',
 'daffodil',
 'rose',
 'coreopsis',
 'rose',
 'bellflower',
 'bellflower',
 'black_eyed_susan',
 'bellflower',
 'tulip',
 'black_eyed_susan',
 'iris',
 'astilbe',
 'coreopsis',
 'bellflower',
 'magnolia',
 'coreopsis',
 'bellflower',
 'black_eyed_susan',
 'tulip',
 'california_poppy',
 'tulip',
 'daffodil',
 'sunflower',
 'water_lily',
 'dandelion',
 'iris',
 'sunflower',
 'iris',
 'black_eyed_susan',
 'su

In [8]:
train_images = np.array(train_images)
train_labels = np.array(train_labels)

In [9]:
train_images.shape

(4000, 128, 128)

In [10]:
train_labels

array(['california_poppy', 'common_daisy', 'dandelion', ..., 'astilbe',
       'magnolia', 'carnation'], dtype='<U16')

In [11]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(train_labels)
train_labels_encoded = le.transform(train_labels)

In [12]:
train_labels_encoded

array([ 4,  6,  9, ...,  0, 11,  5], dtype=int64)

In [13]:
x_train, y_train = train_images, train_labels_encoded

In [14]:
x_train=x_train/255.0

In [15]:
x_train.shape

(4000, 128, 128)

In [ ]:
from keras.utils import to_categorical
y_train_one_hot = to_categorical(y_train)

In [ ]:
y_train_one_hot[4000]

In [ ]:
y_train[4000]

In [ ]:
!pip install keras-tuner

In [16]:
x_train[0].shape

(128, 128)

In [17]:
def build_model(hp):
    model = keras.Sequential([
        keras.layers.Conv2D(
            filters=hp.Int('conv_1_filter', min_value=32, max_value=64, step=16),
            kernel_size=hp.Choice('conv_1_kernel', values = [3,5]),
            activation='relu',
            input_shape=(128,128,1)
        ),
        keras.layers.MaxPooling2D(pool_size=(2, 2)),
        keras.layers.BatchNormalization(),
        keras.layers.Dropout(0.3),
        keras.layers.Conv2D(
            filters=hp.Int('conv_2_filter', min_value=32, max_value=128, step=16),
            kernel_size=hp.Choice('conv_2_kernel', values = [3,5]),
            activation='relu'
        ),
        keras.layers.MaxPooling2D(pool_size=(2, 2)),
        keras.layers.BatchNormalization(),
        keras.layers.Conv2D(
            filters=hp.Int('conv_3_filter', min_value=32, max_value=256, step=16),
            kernel_size=hp.Choice('conv_3_kernel', values = [3,5]),
            activation='relu'
        ),
        keras.layers.BatchNormalization(),
        keras.layers.Conv2D(
            filters=hp.Int('conv_4_filter', min_value=32, max_value=512, step=16),
            kernel_size=hp.Choice('conv_4_kernel', values = [3,5]),
            activation='relu'
        ),
        keras.layers.MaxPooling2D(pool_size=(2, 2)),
        keras.layers.BatchNormalization(),
        keras.layers.Flatten(),
        keras.layers.Dropout(0.5),
        keras.layers.Dense(
            units=hp.Int('dense_1_units', min_value=32, max_value=512, step=16),
            activation='relu'
        ),
        keras.layers.Dropout(0.5),
        keras.layers.Dense(16, activation='softmax')
    ])
    model.compile(optimizer=tf.keras.optimizers.Adam(hp.Choice('learning_rate', values=[1e-2, 1e-3])),
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model

In [18]:
from keras_tuner import RandomSearch
from keras_tuner.engine.hyperparameters import HyperParameters

In [19]:
tuner_search=RandomSearch(build_model,
                              objective='val_accuracy',
                              max_trials=5,directory='output',project_name="Flowers6")

In [20]:
y_train

array([ 4,  6,  9, ...,  0, 11,  5], dtype=int64)

In [21]:
tuner_search.search(x_train,y_train,epochs=3,validation_split=0.1)

Trial 5 Complete [01h 14m 30s]
val_accuracy: 0.057500001043081284

Best val_accuracy So Far: 0.07500000298023224
Total elapsed time: 01h 46m 35s
INFO:tensorflow:Oracle triggered exit


In [22]:
model=tuner_search.get_best_models(num_models=1)[0]

In [23]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 126, 126, 48)      480       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 63, 63, 48)       0         
 )                                                               
                                                                 
 batch_normalization (BatchN  (None, 63, 63, 48)       192       
 ormalization)                                                   
                                                                 
 dropout (Dropout)           (None, 63, 63, 48)        0         
                                                                 
 conv2d_1 (Conv2D)           (None, 59, 59, 64)        76864     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 29, 29, 64)       0

In [24]:
model.fit(x_train, y_train, epochs=10, validation_split=0.1, initial_epoch=3)

Epoch 4/10
113/113 [==============================] - 150s 1s/step - loss: 2.9455 - accuracy: 0.0650 - val_loss: 3.0247 - val_accuracy: 0.0550
Epoch 5/10
113/113 [==============================] - 146s 1s/step - loss: 2.9109 - accuracy: 0.0664 - val_loss: 2.8219 - val_accuracy: 0.0750
Epoch 6/10
113/113 [==============================] - 133s 1s/step - loss: 2.8385 - accuracy: 0.0703 - val_loss: 2.7958 - val_accuracy: 0.0475
Epoch 7/10
113/113 [==============================] - 133s 1s/step - loss: 2.8029 - accuracy: 0.0681 - val_loss: 2.7749 - val_accuracy: 0.0450
Epoch 8/10
113/113 [==============================] - 133s 1s/step - loss: 2.7569 - accuracy: 0.0689 - val_loss: 2.8025 - val_accuracy: 0.0400
Epoch 9/10
113/113 [==============================] - 136s 1s/step - loss: 2.7742 - accuracy: 0.0728 - val_loss: 2.7791 - val_accuracy: 0.0475
Epoch 10/10
113/113 [==============================] - 147s 1s/step - loss: 2.7597 - accuracy: 0.0703 - val_loss: 2.7838 - val_accuracy: 0.047